name: source_gen_demo
description: A source_gen package demo

environment:
  sdk: '>=2.8.1 <3.0.0'

scripts:
  update_example_deps:
    - cd example_usage && pub get
    - cd ..
  update_generator_deps: 
    - cd my_generators && pub get
    - cd ..
  update_deps: 
    - $update_example_deps
    - $update_generator_deps
  gencode: 
    - cd example_usage && fvm flutter pub run build_runner build
    - cd ..
  gencode_watch: 
    - cd example_usage && pub run build_runner watch