targets:
  $default:
    builders:
      my_generators|functionUnwrap:
        enabled: True
        generate_for:
          - test/**/*.source.dart
          - test/*.source.dart
#          - test/unwrap_async/input.source.dart
      my_generators|infoGeneratorBuilder:
        enabled: True
        generate_for:
          - test/**/*
          - test/*