// Mocks generated by Mockito 5.0.8 from annotations
// in example_usage/model.dart.
// Do not manually edit this file.

import 'package:example_usage/model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Cat].
///
/// See the documentation for Mockito's code generation for more information.
class MockCat extends _i1.Mock implements _i2.Cat {
  MockCat() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String sound() =>
      (super.noSuchMethod(Invocation.method(#sound, []), returnValue: '')
          as String);
  @override
  int walk() =>
      (super.noSuchMethod(Invocation.method(#walk, []), returnValue: 0) as int);
}
